### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by JosephSmarsh** [JosephSmarsh/Raspberry-Pi-Inventory-Checker#1]
# TODO 
- [x] Create a script to create a Constants.py file, as well as update the Constants.py and config.ini file (To be run on setup)
- [x] Expand to search for all items at microcenter ( Add option to print name of item, and how many are in stock)
- [x] Update main to run one while loop and three if statements:
```
while true:
    if y:
    if n:
    if notif:
    time.sleep
```
- [ ] Change error handling: Add error messages and add an option to create a log file. 
- [x] Expand project to check national distributers of pi's as well as some more local options.
* For microcenter - Tail of URL contains store number, add location option to check various microcenter locations then expand to other national distributers
- [ ] Find a more reliable option for keeping the script on time and not falling off of time.
- [ ] Change notification sending so that when stock is in, it doesn't send a notification every time the stock changes, just when it returns to being out of stock again. 
- [ ] Update Readme
- [x] change nested if to if and
- [ ] make inventory check a class 
- [x] add store number to settings and integrate into script 
- [x] change setup.py to config.py
- [x] move store list to config, print store list during config setup then ask for user input checked against current store list store numbers, add store number to tail end of link
- [ ] Add predefined links option for popular items (graphics cards, raspberry pi's etc) (won't be maintained) 
- [x] Change stock check import to single line ( from stock checker import (imports))
- [ ] If error, try to restart script several times, then force close 
- [ ] Add current price check
- [ ] Dynamically search page for information
- [ ] Figure out running headless, without ssh (bash) or something
- [ ] Add breakpoints that log
- [x] Add current store option, gets info from the header
- [x] Check for valid pushsafer key and device id (Try to send test notification, if it fails return false, if it makes it return true)(If fails send to setup script)
- [x] Only check that current pushsafer is valid once, if values are valid, store them, and check if they are in the config. If they are in the config don't sent test notification
- [ ] Add item name to send notification 
- [x] Figure out why cant get store list from link that has store number, invalidates the store number
- [x] No link in the config breaks the entire program
- [ ] Separate script to build locations list?
- [ ] Clean up no link problem add base link? or make it a class? add everything to one file? Something about try except for link or location link slowed script wayyy down (Try except for check inventory and check product name) Or website is just slowwww
- [ ] Be careful not to query link too often, keep links outside of the functions, except for check inventory which only runs once every refresh cycle
- [ ] add print statements to see how many times functions are run (.get())
